# Basic Settings
appName: netflix
namespace: dev
replicas: 1

# Image Settings
image:
  repository: azax1234/netflix-clone
  #repository: sevenajay/netflix
  tag: "v0.2.0"
  pullPolicy: IfNotPresent

# Service Settings
service:
  name: netflix-svcs-dev
  type: LoadBalancer
  port: 80