# Basic Settings
appName: netflix
namespace: dev
replicas: 1

# Image Settings
image:
  repository: azax1234/netflix-clone
  #repository: sevenajay/netflix
  tag: "v19.50.0"
  pullPolicy: IfNotPresent

# Resource capacity Settings
requests:
  memory: "1B" 
  cpu: "1m"
limits:
  memory: "1B" 
  cpu: "1m"  

# Service Settings
service:
  name: netflix-svcs-dev
  type: LoadBalancer
  port: 80