# Basic Settings
appName: netflix
namespace: dev
replicas: 1

# Image Settings
image:
  repository: azax1234/netflix-clone
  #repository: sevenajay/netflix
  tag: "v19.4.0"
  pullPolicy: IfNotPresent

# Resource capacity Settings
requests:
  memory: "0m" 
  cpu: "250m"
limits:
  memory: "0m" 
  cpu: "500m"  

# Service Settings
service:
  name: netflix-svcs-dev
  type: LoadBalancer
  port: 80